### ISSUE TITLE
Development Script

### ISSUE THREAD

**Issue by nathfreder** [RefreshAV/spark-west#5]
The host should be `localhost` because `0.0.0.0` is blocked by Firebase automatically. The `cross-env` command is just an extra dependency because the variable is set by default. The port probably shouldn't be set since if it isn't available, errors will be thrown ❤️.  https://github.com/RefreshAV/spark-west/blob/2723964ceaa7ba6c6527c1c43735eb0636965f6d/package.json#L9

**Comment by nathfreder** [comment]
@Jellycream

**Comment by nathfreder** [comment]
@Jellycream

**Comment by Jellycream** [comment]
Yeah I know, I set it as that because port 0.0.0.0 is accessible by other computers on the network, so I could test it on my phone without having to deploy the site. if you want to be able to login just go to localhost:8000. It was kind of just a quick and dirty solution for testing that I'll change later

**Comment by nathfreder** [comment]
👍 , an alternative to that solution is just running `npm run-script dev -- --host 0.0.0.0` instead. It adds on the `host` flag and does not by default use `0.0.0.0`
